<div class="page-title">
    <h1><?php echo $this->__('Bạn đã quên mật khẩu?') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<ul class="messages"><li class="success-msg"><ul><li style="text-align: justify;"><span>Nếu có tài khoản đăng ký với email <strong><?php echo $this->getRequest()->getParam('m') ?></strong>, bạn sẽ nhận được email để thiết lập lại mật khẩu.<p>Vui lòng kiểm tra email của bạn.</p></span></li></ul></li></ul>