<div class="reg-success flr width-70">
	<h3><?php echo $this->__('Xin chúc mừng !!') ?></h3>
	
	<p><?php echo $this->__('Bạn đã đăng ký thành công.Để kích hoạt tài khoản của bạn, vui lòng nhấn vào đường dẫn trong email ICONIC gửi đến bạn.') ?></p>
	<p><?php echo $this->__('Nếu bạn không nhận được email kích hoạt vui lòng kiểm tra <strong>Hộp thư Bulk/Spam</strong>.') ?></p>
	<br />
	<p>Trở về <a title="Trang chủ" href="/">Trang chủ</a> hoặc <a href="/<?php echo $this->helper('job')->getLoginUrl() ?>" title="Đăng nhập">Đăng nhập</a> lại.</p>
</div>
<!-- Phong Google Conversion Tag -->
<!-- Google Code for Sign-up Iconicvn.com Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 975271206;
var google_conversion_language = "en";
var google_conversion_format = "2";
var google_conversion_color = "ffffff";
var google_conversion_label = "PllwCIq90gkQpuqF0QM";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/975271206/?label=PllwCIq90gkQpuqF0QM&amp;guid=ON&amp;script=0"/>
</div>
</noscript><!-- End Phong Google Conversion Tag -->

<!-- Google Code for Sign-up Conversion Page --> 
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 964610057;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "J2StCJfosgkQiZD7ywM"; var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript"  
src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt=""  
src="//www.googleadservices.com/pagead/conversion/964610057/?label=J2StCJfosgkQiZD7ywM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
