<div id="page-title">
	<h2 class="blue-tit text-blue">
		<?php echo $this->__(Mage::getStoreConfig('clnews/news/title')) ?>
	</h2>
</div>

<div id="blog-content" class="fll width-65">
	<?php $item = $this->getNewsitem(); ?>
	<h1 class="text-blue">
		<a href="<?php echo str_replace('clnews', $this->getAlias(), $item->getUrl()) ?>" title="<?php echo $item->getTitle() ?>">
			<?php echo $item->getTitle() ?>
		</a>
	</h1>
	<?php if (Mage::helper('clnews')->showDate()): ?>
	    <span class="date"><?php echo Mage::helper('job')->formatDate($item->getNewsTime()) ?></span>	    
	    <?php if ($item->getAuthor()): ?>
	    <span class="author"><span class="line">|</span><?php echo $this->__('Đăng bởi') ?> <strong><?php echo $item->getAuthor() ?></strong></span>
	    <?php endif; ?>
	<?php endif; ?>
	<?php if (Mage::helper('clnews')->showCategory()): ?>
	    <?php if ($this->getCategoryByNews($item->getID())->getData('title') != ''): ?>
	        <span class="date">&nbsp;|&nbsp; <?php echo $this->getCategoryByNews($item->getID())->getData('title'); ?></span>
	    <?php endif; ?>
	<?php endif; ?>
	
	<div class="social">
	    <?php if (Mage::helper('clnews')->getGoogleAccess()): ?>
	        <script type="text/javascript">
	            (function() {
	                var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
	                po.src = 'https://apis.google.com/js/plusone.js';
	                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
	                <?php if (isset($comments) && count($comments)): ?>
	                    AjaxSend(1, <?php echo $item->getID() ?>, false);
	                <?php endif ?>
	            })();
	        </script>
	        <div class="google_button"><g:plusone></g:plusone></div>
	    <?php endif; ?>
	    <?php if (Mage::helper('clnews')->getFaceBookAccess()): ?>
	        <div id="fb-root"></div>
	        <script>(function(d, s, id) {
	          var js, fjs = d.getElementsByTagName(s)[0];
	          if (d.getElementById(id)) return;
	          js = d.createElement(s); js.id = id;
	          js.src = "//connect.facebook.net/<?php echo Mage::app()->getLocale()->getDefaultLocale() ?>/all.js#xfbml=1";
	          fjs.parentNode.insertBefore(js, fjs);
	        }(document, 'script', 'facebook-jssdk'));</script>
	        <div class="fb-like" data-send="false" data-layout="button_count" data-width="110" data-show-faces="false"></div>
	    <?php endif; ?>
	    <?php if (Mage::helper('clnews')->getLinkedInAccess()): ?>
	        <script src="http://platform.linkedin.com/in.js" type="text/javascript"></script>
	        <script type="IN/Share" data-counter="right"></script>
	    <?php endif; ?>
	    <?php if (Mage::helper('clnews')->getTwitterAccess()): ?>
	        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	        <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
	    <?php endif; ?>
	    <!--
	    <a href="<?php echo $item->getUrl() ?>?mode=print" class="print-btn"><?php echo $this->__('Print Version'); ?></a>
	    -->
	</div>
	
	<?php if ($item->getImageFullContent()): ?>
	    <div class="news_image">
	        <?php $imageSize = $this->getFullImageSize($item) ?>
	        <img src="<?php echo Mage::helper('clnews')->resizeImage(str_replace('clnews/', '', $item->getImageFullContent()), $imageSize['width'], $imageSize['height'], 'clnews'); ?>" />
	    </div>
	<?php endif; ?>
	
	<div class="news">
	    <?php echo $this->contentFilter($item->getFullContent()); ?>
	    <?php if (Mage::helper('clnews')->showAuthor()): ?>
	        <?php if ($item->getAuthor()): ?>
	            <span><?php echo $this->__('Author: ').$item->getAuthor(); ?></span>
	        <?php endif; ?>
	    <?php endif; ?>
	</div>
	
	<p>
	<?php if (Mage::helper('clnews')->getTagsAccess()): ?>
	    <?php if ($item->getTags()): ?>
	    <?php $arr = preg_split('/,/', $item->getTags()); ?>
	    <?php $tags = ''; ?>
	    <?php $count = count($arr); ?>
	    <?php $k = 1; ?>
	    <?php foreach ($arr as $val): ?>
	    <?php if ($k == $count): ?>
	    <?php $tags .= '<a href="' . $this->getUrl(Mage::helper('clnews')->getRoute() . '/index/index/q/' . urlencode(trim($val)) . '/') . '" >' . trim($val) . '</a> '; ?>
	    <?php else: ?>
	    <?php $tags .= '<a href="' . $this->getUrl(Mage::helper('clnews')->getRoute() . '/index/index/q/' . urlencode(trim($val)) . '/') . '" >' . trim($val) . '</a>, '; ?>
	    <?php endif; ?>
	    <?php $k++; ?>
	    <?php endforeach; ?>
	    <img src="<?php echo $this->getSkinUrl('css/clnews/images/i-tags.gif')?>"/>&nbsp;<?php echo $tags; ?>
	    <?php endif; ?>
	<?php endif; ?>
	</p>
	
	<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<script type="text/javascript">
    function AjaxSend(page, id, showLoader)
    {
        var url = "<?php echo Mage::getBaseUrl()?>clnews/newsitem/ajax/id/" + id + "/page/" + page + "/";
        if (showLoader) {
            jQuery("#clloader").css("display","block");
        }
        jQuery.ajax({
            url: url,
            dataType: 'json',
            success: function(data) {
                var content = '';
                jQuery(".comment-item").remove();
                for(var i = 0; i < data['dat'].cnt; i++) {
                    content = '<div id="comment_item_'+ i +'" class="comment-item"><h4 class="username">'+ data['collection'][i].user +'</h4> <?php echo $this->__("posted on")?> ' + data['collection'][i].created_time + '<div>' + data['collection'][i].comment + '</div></div>';
                    jQuery('#comment_block').append(content);
                }
                jQuery(".prev").remove();
                if (typeof(data['dat'].back_url) != 'undefined') {
                    jQuery("#prev").append('<span class="prev" ' + data['dat'].back_url + ' ><?php echo $this->__('Previous') ?></span>');
                }
                jQuery(".next").remove();
                if (typeof(data['dat'].fovard_url) != 'undefined') {
                    jQuery("#next").append('<span class="next" ' + data['dat'].fovard_url + ' ><?php echo $this->__('Next') ?></span>');
                }
                jQuery("#clloader").css("display","none");
            }
        });
        jQuery(".page").removeClass("current");
        var cl = 'page_' + page;
        jQuery("#" + cl).addClass("current");
    }
</script>
<div class="right-col flr width-30">
	<?php echo $this->getChildHtml('right.clnews.categories') ?>
	<?php echo $this->getChildHtml('right.clnews.latest') ?>
</div>