<div class="createcv-success">
	<h3><?php echo $this->__('Xin chúc mừng !!') ?></h3>
	
	<p>Bạn đã tạo hồ sơ thành công tại <a href="/">iconicvn.com</a></p>
	<p>Các chuyên viên Iconic sẽ duyệt hồ sơ của bạn, trước khi giới thiệu đến bạn những công việc phù hợp.</p>
	<br />
	<p>Trang web sẽ tự động trở về trang chủ sau <span id="countdown">5</span> giây nữa.</p>
</div>

<script type="text/javascript">
	(function () {
	    var timeLeft = 5,
	        cinterval;
	
	    var timeDec = function (){
	        timeLeft--;
	        document.getElementById('countdown').innerHTML = timeLeft;
	        if(timeLeft === 0){
	        	window.location = '/';
	            clearInterval(cinterval);
	        }
	    };
	
	    cinterval = setInterval(timeDec, 1000);
	})();
</script>
