<?php $job = $this->getItem() ?>
<?php $jobs = $this->getJobsInCategory() ?>
<div class
<div id="page-title">
	<h2 class="blue-tit text-blue">
		<?php echo $this->__('Ứng tuyển') ?>
	</h2>
</div>
<div class="fll width-60">
	<div id="job-title" class="text-blue">
		<?php echo Mage::helper('job')->renderTitle($job); ?>
	</div>
	<div class="apply-success-message">
		<?php $this->__('Xin chúc mừng!') ?>
		<?php $this->__('Bạn đã ứng tuyển thành công.') ?>
	</div>
</div>
<div class="flr width-35">
	<div class="heading">
		<h4 class="blue-tit text-blue"><?php echo $this->__('Các công việc cùng ngành nghề') ?></h4>
	</div>
	<ul>
		<?php foreach($jobs as $jb): ?>
			<li></li>
		<?php endforeach; ?>
	</ul>
	<a class="text-blue view-more-category" href="<?php echo Mage::helper('job')->getCategoryUrl($job->getCategoryId()); ?>"><?php echo $this->__('Xem thêm') ?></a>
</div>
