<div class="create-cv">
    <div class="page-title">
        <h1><?php echo $this->__('Tạo hồ sơ') ?></h1>
    </div>
    <form action="/<?php echo Mage::helper('job')->getCreateCVUrl() ?>" method="post" id="form-validate">
    	<div class="row heading">
    		<span><?php echo $this->__('Thông tin chung') ?></span>
    	</div>
    	<div class="row row2">
    		<input readonly required type="text" class="first" id="ho" name="ho" placeholder="<?php echo $this->__('Họ') ?>" value="<?php echo $this->getCustomer()->getLastname() ?>" />
    		<input readonly required type="text" class="last" id="ten" name="ten" placeholder="<?php echo $this->__('Tên') ?>" value="<?php echo $this->getCustomer()->getFirstname() ?>" />
    	</div>
    	
    	<div class="row row3">
    		<select required id="day" class="first" name="day">
    			<option value=""><?php echo $this->__('Ngày') ?></option>
            	<?php 
            	for($i = 1; $i <= 31;$i++): ?>
            	<option <?php echo ($this->getFormData()->getDay()==$i) ? 'selected="selected"' : '' ?> value="<?php echo $i ?>"><?php echo $i ?></option>
            	<?php endfor; ?>
    		</select>
    		<select required id="month" name="month" class="middle">
    			<option value=""><?php echo $this->__('Tháng') ?></option>
            	<?php 
            	for($i = 1; $i <= 12;$i++): ?>
            	<option <?php echo ($this->getFormData()->getMonth()==$i) ? 'selected="selected"' : '' ?> value="<?php echo $i ?>"><?php echo $this->__('Tháng') .' '. $i ?></option>
            	<?php endfor; ?>
    		</select>
    		<input readonly class="last select" id="year" type="text" name="year" value="<?php echo $this->getCustomer()->getBirthYear() ?>" />
    	</div>
    	
    	<div class="row row2 clearfix">
    		<input readonly type="text" id="sex" class="first select" name="sex" value="<?php echo $this->getCustomer()->getSex() ?>" />
    		<select required name="nation" id="nation" class="last">
    			<option value="">Quốc tịch</option>
    			<option value="Việt Nam">Việt Nam</option>
    			<option value="Nước ngoài">Nước ngoài</option>
    		</select>
    	</div>
    	
    	<div class="row row1">
    		<input required type="text" name="address" id="address" placeholder="Địa chỉ cư trú" />
    	</div>
    	
    	<div class="row row2">
    		<input readonly class="first select" type="text" id="location" name="location" value="<?php echo Mage::getModel('job/listlocation')->load($this->getCustomer()->getLocation())->getName() ?>" />
    		
    		<select required name="country" id="country" class="last">
    			<option value="">Quốc gia</option>
    			<option value="Việt Nam">Việt Nam</option>
    			<option value="Malaysia">Malaysia</option>
    			<option value="Nhật Bản">Nhật Bản</option>
    		</select>
    	</div>
    	
    	<div class="row row2">
    		<input required type="number" class="first" name="phone" id="phone" placeholder="Di động" />
    		<input readonly required type="text" class="last" name="email" id="email" placeholder="Email" value="<?php echo $this->getCustomer()->getEmail() ?>" />
    	</div>
    	
    	<div class="row row3">
    		<input required type="number" class="first" name="salary" id="salary" placeholder="Mức lương hiện tại" />
    		<select required class="mid" name="currency" id="currency">
    			<option value="USD">USD</option>
    			<option value="VND">VND</option>
    		</select>
    		<select required class="last" name="salarytype" id="salarytype">
    			<option value="Gross">Gross</option>
    			<option value="NET">NET</option>
    		</select>
    	</div>
    	
    	<div class="row heading">
    		<span>Công việc mong muốn</span>
    	</div>
    	
    	<div class="row row3">
    		<input required type="number" class="first" name="salary2" id="salary2" placeholder="Mức lương mong muốn" />
    		<select required class="mid" name="currency2" id="currency2">
    			<option value="USD">USD</option>
    			<option value="VND">VND</option>
    		</select>
    		<select required class="last" name="salarytype2" id="salarytype2">
    			<option value="Gross">Gross</option>
    			<option value="NET">NET</option>
    		</select>
    	</div>
    	
    	<div class="row row2">
    		<select required class="first" name="category" id="category">
    			<option value="">Ngành nghề</option>
				<?php echo $this->getCategoryList($this->getFormData()->getCategory()) ?>
    		</select>
    		<select required class="last" name="function" id="function">
    			<option value="">Chức năng</option>
				<?php echo $this->getFunctionList($this->getFormData()->getFunction()) ?>
    		</select>
    	</div>
    	
    	<div class="row row2">
    		<select required class="first" name="location2" id="location2">
    			<option value="">Địa điểm</option>
    			<?php $list = Mage::getModel('job/listlocation')->getCollection() ?>
				<?php foreach($list as $loc): ?>
					<option <?php echo ($this->getFormData()->getLocation2()==$loc->getId()) ? 'selected="selected"' : '' ?> value="<?php echo $loc->getName() ?>"><?php echo $loc->getName() ?></option>
				<?php endforeach; ?>
    		</select>
    		<select required class="last" name="level" id="level">
    			<option value="">Cấp độ công việc</option>
    			<?php $list = Mage::getModel('job/level')->getCollection() ?>
				<?php foreach($list as $loc): ?>
					<option <?php echo ($this->getFormData()->getLevel()==$loc->getId()) ? 'selected="selected"' : '' ?> value="<?php echo $loc->getName() ?>"><?php echo $loc->getName() ?></option>
				<?php endforeach; ?>
    		</select>
    	</div>
    	
    	<div class="row heading">
    		<span>Trình độ học vấn</span>
    		<div class="last">
	    		<input required type="radio" name="education" value="1" /> Nước ngoài
	    		<input required type="radio" name="education" value="2" /> Việt Nam
    		</div>
    	</div>
    	
    	<div class="row row2">
    		<input required type="text" class="first" name="school" placeholder="Tên trường" />
    		<input required type="text" class="last" name="spec" placeholder="Chuyên ngành" />
    	</div>
    	
    	<div class="row row2">
    		<select required name="degree" id="degree" class="first">
    			<option value="">Bằng cấp</option>
    			<option value="Trung cấp">Trung cấp</option>
    			<option value="Cao đẳng">Cao đẳng</option>
    			<option value="Đại học">Đại học</option>
    			<option value="Thạc sĩ">Thạc sĩ</option>
    			<option value="Tiến sĩ">Tiến sĩ</option>
    		</select>
    		<select required name="graduate" id="graduate" class="last">
    			<option value="">Năm tốt nghiệp</option>
    			<?php 
            	$y = (int) Date('Y');
            	for($i = $y; $i >= $y-40;$i--): ?>
            	<option <?php echo ($this->getFormData()->getGraduate()==$i) ? 'selected="selected"' : '' ?> value="<?php echo $i ?>"><?php echo $i ?></option>
            	<?php endfor; ?>
    		</select>
    	</div>
    	
    	<div class="row heading">
    		<span>Kinh nghiệm</span>
    		<div class="last">
    			<input type="checkbox" name="newgraduate" id="newgraduate" value="1"/> Tôi vừa mới ra trường, chưa có kinh nghiệm làm việc
    		</div>
    	</div>
    	
    	<div class="row row2">
    		<select required class="first" name="category2" id="category2">
    			<option value="">Ngành nghề</option>
				<?php echo $this->getCategoryList($this->getFormData()->getCategory2()) ?>
    		</select>
    		<select required class="last" name="function2" id="function2">
    			<option value="">Chức năng</option>
				<?php echo $this->getCategoryList($this->getFormData()->getFunction2()) ?>
    		</select>
    	</div>
    	
    	<div class="row row2">
    		<select required class="first" name="level2" id="level2">
    			<option value="">Cấp độ công việc</option>
    			<?php $list = Mage::getModel('job/level')->getCollection() ?>
				<?php foreach($list as $loc): ?>
					<option <?php echo ($this->getFormData()->getLevel2()==$loc->getId()) ? 'selected="selected"' : '' ?> value="<?php echo $loc->getName() ?>"><?php echo $loc->getName() ?></option>
				<?php endforeach; ?>
    		</select>
    		<select name="exp" required id="exp" class="last">
    			<option value="">Số năm kinh nghiệm</option>
    			<?php for($i=0;$i<41;$i++): ?>
    			<option value="<?php echo $i ?>"><?php echo $i ?> năm</option>
    			<?php endfor; ?>
    		</select>
    	</div>
    	
    	<div class="row row1">
    		<textarea placeholder="Chi tiết công việc" name="detail" id="detail"></textarea>
    	</div>
    	
    	<div class="row heading">
    		<span>Ngôn ngữ</span>
    	</div>
    	
    	<div class="row lang">
    		<div class="text">
    			Tiếng Nhật
    		</div>
    		<select required name="jp" id="jp">
    			<option value="">Cấp độ</option>
    			<option value="Bản ngữ">Bản ngữ</option>
    			<option value="Cao cấp">Cao cấp</option>
    			<option value="Trung cấp">Trung cấp</option>
    			<option value="Sơ cấp">Sơ cấp</option>
    			<option value="Không">Không</option>
    		</select>
    	</div>
    	
    	<div class="row lang">
    		<div class="text">
    			Tiếng Anh
    		</div>
    		<select required name="en" id="en">
    			<option value="">Cấp độ</option>
    			<option value="Bản ngữ">Bản ngữ</option>
    			<option value="Cao cấp">Cao cấp</option>
    			<option value="Trung cấp">Trung cấp</option>
    			<option value="Sơ cấp">Sơ cấp</option>
    			<option value="Không">Không</option>
    		</select>
    	</div>
    	
    	<div class="row lang">
    		<div class="text">
    			Tiếng Việt
    		</div>
    		<select required name="vn" id="vn">
    			<option value="">Cấp độ</option>
    			<option value="Bản ngữ">Bản ngữ</option>
    			<option value="Cao cấp">Cao cấp</option>
    			<option value="Trung cấp">Trung cấp</option>
    			<option value="Sơ cấp">Sơ cấp</option>
    			<option value="Không">Không</option>
    		</select>
    	</div>
    	
    	<div class="row lang">
    		<textarea placeholder="Thêm trình độ ngoại ngữ khác" name="otherlang" id="otherlang"></textarea>
    	</div>
    	
    	<div class="row heading">
    		<span>Kỹ năng</span>
    	</div>
    	
    	<div class="row lang">
    		<textarea name="skill" id="skill"></textarea>
    	</div>
    	
    	<div class="row">
    		<input required type="radio" name="decide" value="Tôi muốn tìm việc/chuyển việc ngay bây giờ" /> Tôi muốn tìm việc/chuyển việc ngay bây giờ<br />
    		<input required type="radio" name="decide" value="Tôi muốn chuyển nếu có công việc/công ty tốt hơn" /> Tôi muốn chuyển nếu có công việc/công ty tốt hơn<br />
    		<input required type="radio" name="decide" value="Tôi muốn chuyển việc trong tương lai (sau 1 năm)" /> Tôi muốn chuyển việc trong tương lai (sau 1 năm)<br />
    	</div>
    	
    	<div class="row">
    		<input type="submit" value="Gửi" name="submit" />
    	</div>
    </form>
</div>
<script>
(function($){
	$(document).ready(function(){
		$('select').each(function() {
			if ($(this).val() != '') {
				$(this).css('color', 'black');
			}
		});
		$('#newgraduate').on('change', function(){
			if($(this).prop('checked')==true){
				$('#category2, #function2, #level2, #exp, #detail').prop('disabled', true);
			}else{
				$('#category2, #function2, #level2, #exp, #detail').prop('disabled', false);
			}
		});
	});
})(jQuery);
</script>