<?php if($this->getData('item')): ?>
     <br />
   <div class="two-third">      
      <?php if($this->getData('item')->getStatus() == 'awaiting'): ?>
        <p class="information-box">You have submitted this statement which is awaiting approval. It is not available for betting or public display yet.</p>
      <?php elseif($this->getData('item')->getStatus() == 'waiting'): ?>
        <p class="information-box">Betting deadline is past. This statement is awaiting the event.</p>
      <?php elseif($this->getData('item')->getStatus() == 'closed'): ?>
        <p class="information-box">This statement is closed.<br />Decision: <?php if($this->getData('item')->getDecision() == 1){echo 'True';}else{echo 'False';} ?></p>
      <?php endif; ?>
      </p> 
      <h1 class="line-divider"><?php echo $this->getData('item')->getTitle()    ?></h1>
      <?php echo $this->getData('item')->getContent()    ?>
      <br /><br /><br />
      <h4>Info</h4>
      <strong>Opening date:</strong> <?php echo Mage::helper('article')->dateFormat($this->getData('item')->getCreatedTime()) ?><br />
      <strong>Bet deadline:</strong> <?php echo Mage::helper('article')->dateFormat($this->getData('item')->getDeadlineTime()) ?><br />
      <strong>Event date:</strong> <?php echo Mage::helper('article')->dateFormat($this->getData('item')->getEventTime()) ?><br />
      <strong>Category:</strong> <?php echo $this->getData('item')->getCategory() ?><br />
      <strong>Total agree bets:</strong> <?php echo $this->getData('item')->getAgree() ?><br />
      <strong>Total disagree bets:</strong> <?php echo $this->getData('item')->getDisagree() ?><br />
      <strong>Total weighted agree bets:</strong> <?php echo $this->getData('item')->getAgreeWeight() ?><br />
      <strong>Total weighted disagree bets:</strong> <?php echo $this->getData('item')->getDisagreeWeight() ?><br />
      <br /><br />
   </div>
   <div class="one-third last">
      <br /><br />
      <?php if($this->getData('item')->getStatus() == 'available'): ?>
      <p class="download-box">Place your bet here.<br />Current time weight is <?php echo Mage::helper('article')->getTimeWeight($this->getData('item')->getDeadlineTime()) ?>.</p>
      <div class="filter">
         <li></li>
         <li class="agree"><?php echo $this->getData('item')->getAgree() ?></li>
         <li class="disagree"><?php echo $this->getData('item')->getDisagree() ?></li>
         <li class="active"><?php echo Mage::helper('article')->timeCountdown($this->getData('item')->getDeadlineTime(), $this->getData('item')->getStatus()) ?></li>
      </div>
      	  <?php if(Mage::getSingleton('customer/session')->getCustomer()->getId()): ?>
	      <form id="betForm" name="betForm" action="<?php echo $this->getUrl('article/index/bet') ?>" method="post">         
	         <fieldset id="btcForm">
	            Amount:<br /><input type="number" step="0.01" min="0" name="amount" id="id_amount" />
	         </fieldset>
	         <ul>
	            <li><label for="id_betSide_0"><input type="radio" id="id_betSide_0" value="1" name="betSide" /> Agree</label></li>
	            <li><label for="id_betSide_1"><input type="radio" id="id_betSide_1" value="2" name="betSide" /> Disagree</label></li>
	         </ul>
	         <input type="hidden" name="itemId" value="<?php echo $this->getData('item')->getArticleId(); ?>" />
	         <div id="contactForm"><input type="submit" value="Bet" name="Bet" id="submit" /></div>
	      </form>
	      <?php else : ?>
	      You need to <a href="<?php echo $this->getUrl('customer/account/login') ?>">login</a> to bet.
	      <?php endif; ?>
      <?php endif; ?>
      <?php $bets = Mage::getModel('article/bet')->getCollection()
                        ->addFieldToFilter('customer_id', Mage::getSingleton('customer/session')->getCustomer()->getId())
                        ->addFieldToFilter('article_id', $this->getData('item')->getArticleId())
                        ->load()              
      ?>
      <?php if(count($bets) > 0): ?>
      <h4>Your bets on this item</h4>
            <?php foreach($bets as $bet): ?>
		      <?php echo $bet->getAgree() == 0 ? 'Disagree for '.$bet->getDisagree().' (Weighted: '.$bet->getDisagreeWeight().').<br />': 'Agree for '.$bet->getAgree().' (Weighted: '.$bet->getAgreeWeight().').<br />' ?>
            <?php endforeach; ?>
      <?php endif; ?>
   </div>
   <div class="clear "></div>
<script type="text/javascript">
//< ![CDATA[
  var myForm= new VarienForm('betForm', true);
//]]>

jQuery('#betForm').submit(function() {
    if(jQuery('#id_amount').val() > <?php echo Mage::getSingleton('customer/session')->getCustomer()->getBalance() ?>){
        jQuery('#id_amount').after('<ul class="errorlist"><li>Your balance is not enough.</li></ul>');
        return false;
    }
});
</script>
<?php else: ?>
<br />
<div class="two-third">
    <p class="error-box">This page doesn't exist or you do not have permission to view it.</p>
</div>
<?php endif; ?>