    <br />
    
   <form action="<?php echo $this->getBaseUrl() ?>article/index/new" method="post" id="new_article">
      <div class="one-half">
         <fieldset id="contactForm">
            <p>
               Statement:<br /><input id="id_title" type="text" name="title" maxlength="100"/>
            </p>
            <p>
               Description:<br /><textarea id="id_description" rows="10" cols="40" name="content"></textarea>
            </p>
         </fieldset>
      </div>
      <div class="one-helf last">
         <fieldset id="btcForm">
            <p>
               Category:<br />
               <select name="category" id="id_category" class="required-entry">                  
                  <option></option>
                  <?php foreach($this->getData('categories') as $k => $v): ?>
                  <option value="<?php echo $v['name'] ?>"><?php echo $v['name'] ?></option>                  
                  <?php endforeach; ?>                  
               </select>
            </p>
            <br />Your bet:<br /><input type="number" maxlength="11" step="0.01" min="0" name="betAmount" id="id_betAmount" class="required-entry validate-number"/>
         </fieldset>
         <fieldset>
            <ul>
               <li><label for="id_betSide_0"><input type="radio" id="id_betSide_0" value="1" name="betSide"/> Agree</label></li>
               <li><label for="id_betSide_1"><input type="radio" id="id_betSide_1" value="2" name="betSide"/> Disagree</label></li>
            </ul>
         </fieldset>
      </div>
      <div class="clear "></div>
      <fieldset id="flight">
        	<label style="float: left; margin-right: 100px;"> 
        	Event date<br/> 
        	<input class="date" id="event" name="eventtime"/><a href="#" class="caltrigger"></a> 
        	</label>
        	<label> 
        	Bet deadline<br/>  
        	<input class="date" id="deadline" maxlength="524288" name="deadlinetime" size="20" tabindex="0" title=""/><a href="#" class="caltrigger"></a> 
        	</label>
        </fieldset>
      <div id="contactForm"><input type="submit" value="Submit" name="submit" id="submit"/></div>
   </form>
   <p>Submission fee of 0.1 will apply.<br />
      Moderators may make editorial changes.<br />
      All dates correspond to end of day Eastern Time.<br />
      You can give us <a href="mailto:john@reid.cc">feedback</a> if you have any troubles.
   </p>	
   <script type="text/javascript">
//< ![CDATA[
  var myForm= new VarienForm('new_article', true);
//]]>
jQuery('#new_article').submit(function() {
    if(jQuery('#id_betAmount').val() > <?php echo Mage::getSingleton('customer/session')->getCustomer()->getBalance() ?>){
        jQuery('#id_betAmount').after('<ul class="errorlist"><li>Your balance is not enough.</li></ul>');
        return false;
    }
});
</script>

<script>
    jQuery(function(){
      jQuery.datepicker.setDefaults(
        jQuery.extend(jQuery.datepicker.regional[""])
      );
      jQuery('#event').datepicker({onSelect: function(dateStr) {
        var d = jQuery.datepicker.parseDate('mm/dd/yy', dateStr);  
        var max = jQuery.datepicker.parseDate('mm/dd/yy', dateStr);
        d.setDate(d.getDate() - 2);
        max.setDate(d.getDate() + 1);
        jQuery('#deadline').datepicker('setDate', d);
        jQuery('#deadline').datepicker('option', 'maxDate', max);
      }});
      jQuery("#event").datepicker('option', 'minDate', new Date());
      jQuery("#event").datepicker('option', 'maxDate', "+2y");
      jQuery("#deadline").datepicker();
      jQuery("#deadline").datepicker('option', 'minDate', new Date());    

});
</script>