<?php $blog = $this->getBlog() ?>
<div class="blog-details-content">
	<div class="blog-parents">
		<?php foreach($blog->getParentCats() as $parent): ?>
			<div class="inline parent parent<?php echo $parent->getId() ?>"><?php echo $parent->getName() ?></div>
		<?php endforeach; ?>
	</div>
	
	<!-- Share buttons -->
	<span class="facebook-share">
		<span class='st_fblike_vcount' displayText='Facebook Like'></span>
	</span>
	<span class="twitter-share">
		<a href="" class="twitter-share-button" data-lang="en" data-count="vertical">Tweet</a>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	</span>
	<span class="linkedin-share">
		<script src="//platform.linkedin.com/in.js" type="text/javascript">
		  lang: en_US
		</script>
		<script type="IN/Share" data-counter="top"></script>
	</span>
	<span class="google-share">
		<div class="g-plusone" data-size="tall"></div>
	</span><!-- End Share Buttons -->
	
	<div class="inline"><?php echo $blog->getDate() ?></div>
	<?php $author = Mage::getModel('blog/author')->load($blog->getAuthorId()) ?>
	<div class="inline author">
		<img src="/media/<?php echo $author->getImage() ?>" alt="" width="25" height="25" />
		<a  href="<?php echo $author->getLink() ?>"><?php echo $author->getName() ?></a>
	</div>
	<h1><?php echo $blog->getTitle() ?></h1>
	<div class="blog-cats">
		<?php foreach($blog->getSubCats() as $cat): ?>
			<div class="inline cat"><?php echo $cat->getName() ?></div>
		<?php endforeach; ?>
	</div>
	<div class="full-content">
		<?php echo $blog->getFullContent() ?>
	</div>
</div>
<div id="facebook-comments">
	<div class="fb-comments" data-width="600" data-numposts="5" data-colorscheme="light"></div>
</div>